Fri, 04 May 2018 11:11:22 server.py[line:177] DEBUG Ö¸¶¨ÅäÖÃÎÄ¼þ[conf/setting.ini]¡£
Fri, 04 May 2018 11:11:22 server.py[line:189] INFO Server name: ²âÊÔ
Fri, 04 May 2018 11:11:22 server.py[line:190] INFO Listening on 127.0.0.1:50123
Fri, 04 May 2018 11:11:22 riskmanage.py[line:110] WARNING [0]Account[nan] cast to int failed!
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400008, ³Â¼ÑÓ«, 20) at 1
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400009, ²ÜÐñ±ó, 30) at 2
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400010, Çú´ï, 40) at 3
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400011, ÎâÇ°è¤, 50) at 4
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400012, ÀîÃ÷Î°, 60) at 5
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400013, ÍõÊ÷»ª, 70) at 6
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400014, ÌÀÎÄºÆ, 80) at 7
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400015, ÑÏÉ­, 6000) at 8
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400016, Óà°Øº², 100) at 9
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400017, ÍôÑ©±ù, 110) at 10
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400018, Íõ¿­, 120) at 11
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400019, ·ëÒÕ³¬, 130) at 12
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400020, Ñî½ðº×, 140) at 13
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400021, ÌÆ³ÐÐ­, 150) at 14
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400022, Ëï¿ª¿Æ, 160) at 15
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400023, Àî³¬»Ô, 170) at 16
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400024, Íõ¼ª, 180) at 17
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400025, ÕÔÓî, 190) at 18
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400026, µ³Õþ, 200) at 19
Fri, 04 May 2018 11:11:22 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400027, µËÎÄÁÁ, 210) at 20
Fri, 04 May 2018 11:11:23 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400028, 400028, 220) at 21
Fri, 04 May 2018 11:11:23 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400029, º«½¡, 230) at 22
Fri, 04 May 2018 11:11:23 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400030, ºúÁÖ, 240) at 23
Fri, 04 May 2018 11:11:23 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400031, ÕÔÌÀÒã, 250) at 24
Fri, 04 May 2018 11:11:23 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400032, »ÆÈðÊ¿, 260) at 25
Fri, 04 May 2018 11:11:23 server.py[line:112] DEBUG Waiting for connection.
Fri, 04 May 2018 11:11:26 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:11:29 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:11:32 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:11:35 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:11:38 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:11:41 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:11:44 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:11:47 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:11:50 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:11:53 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:11:56 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:11:59 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:02 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:05 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:08 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:11 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:14 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:17 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:18 server.py[line:116] INFO New Connection Address is ('127.0.0.1', 12373)
Fri, 04 May 2018 11:12:18 server.py[line:112] DEBUG Waiting for connection.
Fri, 04 May 2018 11:12:20 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:23 server.py[line:159] WARNING Error at handle_mew_conn
Fri, 04 May 2018 11:12:23 server.py[line:160] WARNING Address is ('127.0.0.1', 12373).
Fri, 04 May 2018 11:12:23 server.py[line:161] WARNING Traceback (most recent call last):
  File ".\src\server.py", line 131, in handle_new_conn
    data = conn.recv(1024)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\_socket3.py", line 337, in recv
    self._wait(self._read_event)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\_socket3.py", line 157, in _wait
    self.hub.wait(watcher)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 651, in wait
    result = waiter.get()
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 899, in get
    return self.hub.switch()
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 630, in switch
    return RawGreenlet.switch(self)
socket.timeout: timed out

Fri, 04 May 2018 11:12:23 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:24 server.py[line:116] INFO New Connection Address is ('127.0.0.1', 12378)
Fri, 04 May 2018 11:12:24 server.py[line:112] DEBUG Waiting for connection.
Fri, 04 May 2018 11:12:26 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:29 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:31 server.py[line:155] INFO Connection of ('127.0.0.1', 12378) Closed!
Fri, 04 May 2018 11:12:32 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:35 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:38 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:41 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:44 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:47 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:50 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:53 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:56 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:12:59 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:02 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:05 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:08 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:11 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:15 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:18 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:21 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:24 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:27 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:30 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:33 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:36 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:39 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:42 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:45 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:48 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:51 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:54 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:13:57 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:14:00 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:14:03 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:14:06 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:14:09 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:14:12 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:14:19 server.py[line:177] DEBUG Ö¸¶¨ÅäÖÃÎÄ¼þ[conf/setting.ini]¡£
Fri, 04 May 2018 11:14:19 server.py[line:189] INFO Server name: ²âÊÔ
Fri, 04 May 2018 11:14:19 server.py[line:190] INFO Listening on 127.0.0.1:50123
Fri, 04 May 2018 11:14:19 riskmanage.py[line:110] WARNING [0]Account[nan] cast to int failed!
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400008, ³Â¼ÑÓ«, 20) at 1
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400009, ²ÜÐñ±ó, 30) at 2
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400010, Çú´ï, 40) at 3
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400011, ÎâÇ°è¤, 50) at 4
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400012, ÀîÃ÷Î°, 60) at 5
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400013, ÍõÊ÷»ª, 70) at 6
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400014, ÌÀÎÄºÆ, 80) at 7
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400015, ÑÏÉ­, 6000) at 8
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400016, Óà°Øº², 100) at 9
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400017, ÍôÑ©±ù, 110) at 10
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400018, Íõ¿­, 120) at 11
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400019, ·ëÒÕ³¬, 130) at 12
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400020, Ñî½ðº×, 140) at 13
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400021, ÌÆ³ÐÐ­, 150) at 14
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400022, Ëï¿ª¿Æ, 160) at 15
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400023, Àî³¬»Ô, 170) at 16
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400024, Íõ¼ª, 180) at 17
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400025, ÕÔÓî, 190) at 18
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400026, µ³Õþ, 200) at 19
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400027, µËÎÄÁÁ, 210) at 20
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400028, 400028, 220) at 21
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400029, º«½¡, 230) at 22
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400030, ºúÁÖ, 240) at 23
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400031, ÕÔÌÀÒã, 250) at 24
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400032, »ÆÈðÊ¿, 260) at 25
Fri, 04 May 2018 11:14:19 riskmanage.py[line:121] DEBUG (Account, Name, Stop): (400050, 400050, 10000) at 26
Fri, 04 May 2018 11:14:19 server.py[line:112] DEBUG Waiting for connection.
Fri, 04 May 2018 11:14:22 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:14:22 server.py[line:116] INFO New Connection Address is ('127.0.0.1', 12435)
Fri, 04 May 2018 11:14:22 server.py[line:112] DEBUG Waiting for connection.
Fri, 04 May 2018 11:14:25 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:14:28 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:14:29 server.py[line:155] INFO Connection of ('127.0.0.1', 12435) Closed!
Fri, 04 May 2018 11:14:31 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:14:34 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:14:37 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:14:38 server.py[line:116] INFO New Connection Address is ('127.0.0.1', 12440)
Fri, 04 May 2018 11:14:38 server.py[line:112] DEBUG Waiting for connection.
Fri, 04 May 2018 11:14:40 server.py[line:155] INFO Connection of ('127.0.0.1', 12440) Closed!
Fri, 04 May 2018 11:14:40 server.py[line:89] DEBUG Data Recieved.
Fri, 04 May 2018 11:14:43 server.py[line:89] DEBUG Data Recieved.
