[2017-06-28 14:46:08] Waiting for connection
[2017-06-28 14:46:09] New Connection Address is ('127.0.0.1', 1778)
[2017-06-28 14:46:09] Waiting for connection
[2017-06-28 14:46:58] Data Recieved
[2017-06-28 14:46:58] Connection of ('127.0.0.1', 1778) Closed
[2017-06-28 14:47:47] Data Recieved
[2017-06-28 14:48:37] Data Recieved
[2017-06-28 14:49:26] Data Recieved
[2017-06-28 14:50:16] Data Recieved
[2017-06-28 14:51:05] Data Recieved
[2017-06-28 14:51:55] Data Recieved
[2017-06-28 14:52:44] Data Recieved
[2017-06-28 14:53:34] Data Recieved
[2017-06-28 14:54:23] Data Recieved
[2017-06-28 14:55:12] Data Recieved
[2017-06-28 14:56:02] Data Recieved
[2017-06-28 14:56:51] Data Recieved
[2017-06-28 14:57:41] Data Recieved
[2017-06-28 14:58:30] Data Recieved
[2017-06-28 14:59:20] Data Recieved
[2017-06-28 15:00:09] Data Recieved
[2017-06-28 15:00:59] Data Recieved
[2017-06-28 15:01:48] Data Recieved
[2017-06-28 15:02:37] Data Recieved
[2017-06-28 15:03:28] Data Recieved
[2017-06-28 15:04:17] Data Recieved
[2017-06-28 15:05:07] Data Recieved
[2017-06-28 15:05:57] Data Recieved
[2017-06-28 15:06:46] Data Recieved
[2017-06-28 15:07:36] Data Recieved
[2017-06-28 15:08:25] Data Recieved
[2017-06-28 15:09:15] Data Recieved
[2017-06-28 15:10:04] Data Recieved
[2017-06-28 15:10:54] Data Recieved
[2017-06-28 15:11:43] Data Recieved
[2017-06-28 16:10:55] Waiting for connection
[2017-06-28 16:11:09] New Connection Address is ('127.0.0.1', 4618)
[2017-06-28 16:11:09] Waiting for connection
[2017-06-28 16:11:45] Data Recieved
[2017-06-28 16:11:50] Error at handle_mew_conn
[2017-06-28 16:11:50] Address is ('127.0.0.1', 4618)
[2017-06-28 16:11:50] Traceback (most recent call last):
  File "server.py", line 97, in handle_new_conn
    data = conn.recv(1024)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\_socket3.py", line 337, in recv
    self._wait(self._read_event)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\_socket3.py", line 157, in _wait
    self.hub.wait(watcher)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 651, in wait
    result = waiter.get()
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 899, in get
    return self.hub.switch()
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 630, in switch
    return RawGreenlet.switch(self)
socket.timeout: timed out

[2017-06-28 16:11:52] New Connection Address is ('127.0.0.1', 4655)
[2017-06-28 16:11:52] Waiting for connection
[2017-06-28 16:11:53] Error at handle_mew_conn
[2017-06-28 16:11:53] Address is ('127.0.0.1', 4655)
[2017-06-28 16:11:53] Traceback (most recent call last):
  File "server.py", line 97, in handle_new_conn
    data = conn.recv(1024)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\_socket3.py", line 333, in recv
    return _socket.socket.recv(self._sock, *args)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

[2017-06-28 16:11:55] New Connection Address is ('127.0.0.1', 4663)
[2017-06-28 16:11:55] Waiting for connection
[2017-06-28 16:12:34] Data Recieved
[2017-06-28 16:12:34] Connection of ('127.0.0.1', 4663) Closed
[2017-06-28 16:12:38] New Connection Address is ('127.0.0.1', 4682)
[2017-06-28 16:12:38] Waiting for connection
[2017-06-28 16:13:24] Data Recieved
[2017-06-28 16:14:13] Data Recieved
[2017-06-28 16:15:02] Data Recieved
[2017-06-28 16:15:52] Data Recieved
[2017-06-28 16:16:41] Data Recieved
[2017-06-28 16:17:31] Data Recieved
[2017-06-28 16:18:20] Data Recieved
[2017-06-28 16:19:10] Data Recieved
[2017-06-28 16:19:59] Data Recieved
[2017-06-28 16:20:48] Data Recieved
[2017-06-28 16:21:38] Data Recieved
[2017-06-28 16:22:27] Data Recieved
[2017-06-28 16:23:16] Data Recieved
[2017-06-28 16:24:06] Data Recieved
[2017-06-28 16:24:55] Data Recieved
[2017-06-28 16:25:44] Data Recieved
[2017-06-28 16:26:34] Data Recieved
[2017-06-28 16:27:23] Data Recieved
[2017-06-28 16:28:13] Data Recieved
[2017-06-28 16:29:03] Data Recieved
[2017-06-28 16:29:52] Data Recieved
[2017-06-28 16:30:42] Data Recieved
[2017-06-28 16:31:31] Data Recieved
[2017-06-28 16:32:20] Data Recieved
[2017-06-28 16:33:10] Data Recieved
[2017-06-28 16:33:59] Data Recieved
[2017-06-28 16:34:49] Data Recieved
[2017-06-28 16:34:50] Connection of ('127.0.0.1', 4682) Closed
[2017-06-28 16:34:55] New Connection Address is ('127.0.0.1', 5261)
[2017-06-28 16:34:55] Waiting for connection
[2017-06-28 16:35:39] Data Recieved
[2017-06-28 16:35:46] Error at handle_mew_conn
[2017-06-28 16:35:46] Address is ('127.0.0.1', 5261)
[2017-06-28 16:35:46] Traceback (most recent call last):
  File "server.py", line 97, in handle_new_conn
    data = conn.recv(1024)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\_socket3.py", line 337, in recv
    self._wait(self._read_event)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\_socket3.py", line 157, in _wait
    self.hub.wait(watcher)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 651, in wait
    result = waiter.get()
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 899, in get
    return self.hub.switch()
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 630, in switch
    return RawGreenlet.switch(self)
socket.timeout: timed out

[2017-06-28 16:36:19] New Connection Address is ('127.0.0.1', 5408)
[2017-06-28 16:36:19] Waiting for connection
[2017-06-28 16:36:19] Error at handle_mew_conn
[2017-06-28 16:36:19] Address is ('127.0.0.1', 5408)
[2017-06-28 16:36:19] Traceback (most recent call last):
  File "server.py", line 97, in handle_new_conn
    data = conn.recv(1024)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\_socket3.py", line 333, in recv
    return _socket.socket.recv(self._sock, *args)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

[2017-06-28 16:36:28] Data Recieved
[2017-06-28 16:37:04] New Connection Address is ('127.0.0.1', 5452)
[2017-06-28 16:37:04] Waiting for connection
[2017-06-28 16:37:18] Data Recieved
[2017-06-28 16:38:08] Data Recieved
[2017-06-28 16:38:08] Connection of ('127.0.0.1', 5452) Closed
[2017-06-28 16:38:57] Data Recieved
[2017-06-28 16:39:47] Data Recieved
[2017-06-28 16:40:37] Data Recieved
[2017-06-28 16:41:18] New Connection Address is ('127.0.0.1', 5738)
[2017-06-28 16:41:18] Waiting for connection
[2017-06-28 16:41:26] Data Recieved
[2017-06-28 16:41:31] Error at handle_mew_conn
[2017-06-28 16:41:31] Address is ('127.0.0.1', 5738)
[2017-06-28 16:41:31] Traceback (most recent call last):
  File "server.py", line 97, in handle_new_conn
    data = conn.recv(1024)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\_socket3.py", line 337, in recv
    self._wait(self._read_event)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\_socket3.py", line 157, in _wait
    self.hub.wait(watcher)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 651, in wait
    result = waiter.get()
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 899, in get
    return self.hub.switch()
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 630, in switch
    return RawGreenlet.switch(self)
socket.timeout: timed out

[2017-06-28 16:41:35] New Connection Address is ('127.0.0.1', 5746)
[2017-06-28 16:41:35] Waiting for connection
[2017-06-28 16:42:16] Data Recieved
[2017-06-28 16:43:05] Data Recieved
[2017-06-28 16:43:55] Data Recieved
[2017-06-28 16:44:44] Data Recieved
[2017-06-28 16:45:39] Data Recieved
[2017-06-28 16:46:29] Data Recieved
[2017-06-28 16:47:19] Data Recieved
[2017-06-28 16:48:08] Data Recieved
[2017-06-28 16:48:58] Data Recieved
[2017-06-28 16:49:47] Data Recieved
[2017-06-28 16:50:36] Data Recieved
[2017-06-28 16:51:26] Data Recieved
[2017-06-28 16:52:15] Data Recieved
[2017-06-28 16:52:16] Connection of ('127.0.0.1', 5746) Closed
[2017-06-28 16:53:06] Data Recieved
[2017-06-28 16:53:32] New Connection Address is ('127.0.0.1', 6111)
[2017-06-28 16:53:32] Waiting for connection
[2017-06-28 16:53:55] Data Recieved
[2017-06-28 16:54:00] Error at handle_mew_conn
[2017-06-28 16:54:00] Address is ('127.0.0.1', 6111)
[2017-06-28 16:54:00] Traceback (most recent call last):
  File "server.py", line 97, in handle_new_conn
    data = conn.recv(1024)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\_socket3.py", line 337, in recv
    self._wait(self._read_event)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\_socket3.py", line 157, in _wait
    self.hub.wait(watcher)
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 651, in wait
    result = waiter.get()
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 899, in get
    return self.hub.switch()
  File "C:\Program Files\Anaconda3\lib\site-packages\gevent\hub.py", line 630, in switch
    return RawGreenlet.switch(self)
socket.timeout: timed out

[2017-06-28 16:54:03] New Connection Address is ('127.0.0.1', 6120)
[2017-06-28 16:54:03] Waiting for connection
[2017-06-28 16:54:45] Data Recieved
[2017-06-28 16:54:45] Connection of ('127.0.0.1', 6120) Closed
[2017-06-28 16:55:34] Data Recieved
[2017-06-28 17:05:14] Waiting for connection
[2017-06-28 17:05:14] New Connection Address is ('127.0.0.1', 6488)
[2017-06-28 17:05:14] Waiting for connection
[2017-06-28 17:06:03] Data Recieved
[2017-06-28 17:06:53] Data Recieved
[2017-06-28 17:07:42] Data Recieved
[2017-06-28 17:08:32] Data Recieved
[2017-06-28 17:09:21] Data Recieved
[2017-06-28 17:09:21] Connection of ('127.0.0.1', 6488) Closed
[2017-06-28 17:10:17] New Connection Address is ('127.0.0.1', 6621)
[2017-06-28 17:10:17] Waiting for connection
[2017-06-28 17:10:18] Data Recieved
[2017-06-28 17:11:07] Data Recieved
[2017-06-28 17:11:07] Connection of ('127.0.0.1', 6621) Closed
[2017-06-28 17:11:23] New Connection Address is ('127.0.0.1', 6646)
[2017-06-28 17:11:23] Waiting for connection
[2017-06-28 17:11:56] Data Recieved
[2017-06-28 17:12:46] Data Recieved
[2017-06-28 17:12:46] Connection of ('127.0.0.1', 6646) Closed
